language: objective-c
osx_image: xcode13.2
branches:
  only:
    - master

before_install:
  - gem install xcpretty

script:
- swift build
- swift test
after_success: bash <(curl -s https://codecov.io/bash)